---
#
# Installing Logstash
#

# Install Logstash 

- name: Install Logstash with apt
  apt:
   name: logstash
   update_cache: yes
 
   
# Starting Kibana

- name: Starting logstash
  service:
   name: logstash
   state: started
