
# Install Java 

- name: Install Java 8
  apt:
   name: openjdk-8-jre-headless
   state: present
   update_cache: yes

# Install apt-transport-https

- name: Install apt transport
  apt:
   name: apt-transport-https
   state: present
   update_cache: yes